import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Bell, Calculator, Check, ChevronDown, ChevronRight, CircleHelp, ExternalLink, Heart, Info, MapPin, Menu, Plus, Scale, Search, ShieldCheck, SlidersHorizontal, Sparkles, Star, X } from 'lucide-react'
import { products as seedProducts, type Product } from './data/products'
import './App.css'

const formatZar = (value: number) => `R${Math.round(value).toLocaleString('en-ZA')}`

function App() {
  const [products, setProducts] = useState<Product[]>(seedProducts)
  const [catalogSource, setCatalogSource] = useState('local fallback')
  const [query, setQuery] = useState('')
  const [budget, setBudget] = useState(8000)
  const [activeTab, setActiveTab] = useState('Discover')
  const [selected, setSelected] = useState<number[]>([1])
  const [showComparison, setShowComparison] = useState(false)
  const [showCalculator, setShowCalculator] = useState(false)
  const [calculatorProduct, setCalculatorProduct] = useState(products[0])
  const [shipping, setShipping] = useState(480)
  const [duty, setDuty] = useState(360)
  const [vat, setVat] = useState(520)
  const [postalCode, setPostalCode] = useState('8001')
  useEffect(() => {
    fetch('/api/products')
      .then((response) => response.ok ? response.json() : Promise.reject(new Error('Catalog API unavailable')))
      .then((payload: { products: Product[] }) => { setProducts(payload.products); setCatalogSource('catalog API') })
      .catch(() => setCatalogSource('local fallback'))
  }, [])
  const filteredProducts = useMemo(() => {
    const normalizedQuery = query.toLowerCase().trim()
    return products.filter((product) => (!normalizedQuery || `${product.brand} ${product.name}`.toLowerCase().includes(normalizedQuery)) && product.localPrice <= budget)
  }, [budget, products, query])
  const importedTotal = calculatorProduct.importPrice + shipping + duty + vat + 180
  const localSaving = calculatorProduct.localPrice - importedTotal
  const toggleCompare = (id: number) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id].slice(-3))
  const openComparison = () => {
    setShowComparison(true)
    window.setTimeout(() => document.getElementById('compare-section')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0)
  }
  const openCalculator = (product: Product) => { setCalculatorProduct(product); setShipping(product.importShipping); setDuty(Math.round(product.importPrice * 0.1)); setVat(Math.round((product.importPrice + product.importShipping) * 0.15)); setShowCalculator(true) }

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#top" aria-label="Sift home"><span className="brand-mark"><Sparkles size={15} /></span><span>sift<span className="brand-dot">.</span></span></a><nav className="main-nav" aria-label="Main navigation">{['Discover', 'Compare', 'Price watch'].map((tab) => <button className={activeTab === tab ? 'nav-link active' : 'nav-link'} key={tab} onClick={() => { setActiveTab(tab); if (tab === 'Compare') openComparison() }}>{tab}</button>)}</nav><div className="top-actions"><button className="icon-button quiet" title="Price alerts"><Bell size={18} /></button><button className="profile-button"><span className="avatar">JD</span><span className="profile-name">Jamie</span><ChevronDown size={15} /></button><button className="icon-button mobile-menu" title="Open menu"><Menu size={20} /></button></div></header>
    <main id="top">
      <section className="hero-section"><div className="eyebrow"><span className="eyebrow-line" /> SOUTH AFRICA'S SMARTER SHOPPING SHORTLIST</div><h1>Buy the right thing.<br /><em>Keep more of your money.</em></h1><p className="hero-copy">Compare what matters, not just what is cheapest. We turn product quality, local prices and import costs into a clear decision.</p><div className="search-wrap"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products, brands or categories" aria-label="Search products" /><kbd>/</kbd><button className="search-button">Search</button></div><div className="hero-meta"><span><MapPin size={14} /> Prices for Cape Town, 8001</span><span className="meta-divider" /><span><ShieldCheck size={14} /> Independent by design</span><span className="meta-divider" /><span className="source-status">● {catalogSource}</span></div></section>
      <section className="content-section"><div className="section-heading"><div><p className="section-kicker">CURATED FOR YOU</p><h2>Headphones worth hearing about</h2></div><button className="filter-button"><SlidersHorizontal size={17} /> Filters <span className="filter-count">2</span></button></div><div className="category-row">{['All headphones', 'Over-ear', 'Noise cancelling', 'Under R2,000', 'Best battery'].map((category, index) => <button key={category} className={index === 0 ? 'category-chip selected' : 'category-chip'}>{category}</button>)}</div><div className="workspace-grid"><aside className="filter-panel"><div className="filter-title"><span>Refine results</span><button className="reset-button">Reset</button></div><label className="filter-label" htmlFor="budget">Your budget <strong>{formatZar(budget)}</strong></label><input id="budget" className="range-input" type="range" min="1000" max="10000" step="500" value={budget} onChange={(event) => setBudget(Number(event.target.value))} /><div className="range-labels"><span>R1,000</span><span>R10,000+</span></div><div className="filter-group"><span className="filter-label">Shopping route</span><label className="check-row"><input type="checkbox" defaultChecked /> <span>Available locally</span><small>{products.length}</small></label><label className="check-row"><input type="checkbox" defaultChecked /> <span>Worth importing</span><small>12</small></label></div><div className="filter-group"><span className="filter-label">Must have</span><label className="check-row"><input type="checkbox" /> <span>Noise cancelling</span><small>24</small></label><label className="check-row"><input type="checkbox" /> <span>Multipoint</span><small>18</small></label><label className="check-row"><input type="checkbox" /> <span>40+ hour battery</span><small>9</small></label></div><div className="filter-note"><Info size={15} /><span>Prices include local delivery. Import estimates include a range for duties and courier fees.</span></div></aside><div className="results-column"><div className="results-toolbar"><span><strong>{filteredProducts.length}</strong> products matched</span><button className="sort-button">Sort: <strong>Best match</strong> <ChevronDown size={15} /></button></div><div className="product-grid">{filteredProducts.map((product) => <ProductCard key={product.id} product={product} selected={selected.includes(product.id)} onCompare={() => toggleCompare(product.id)} onCalculate={() => openCalculator(product)} />)}</div>{!filteredProducts.length && <div className="empty-state"><CircleHelp size={28} /><h3>No matches at this budget</h3><p>Try increasing your budget or clearing the search.</p></div>}</div></div></section>
      {showComparison && <ComparisonSection products={products.filter((product) => selected.includes(product.id))} onRemove={toggleCompare} />}
      <section className="insight-band"><div className="insight-icon"><Calculator size={24} /></div><div><p className="section-kicker">THE IMPORT CHECK</p><h2>Cheaper overseas is not always cheaper.</h2><p>We estimate the real cost of getting it to your door, then factor in warranty and delivery so your shortlist reflects real life.</p></div><button className="text-button" onClick={() => products[0] && openCalculator(products[0])}>See an example <ArrowUpRight size={17} /></button></section><section className="footer-strip"><span><Sparkles size={15} /> Built for better decisions in South Africa</span><span>{catalogSource} · September 2026</span></section>
    </main>
    {selected.length > 0 && <div className="compare-tray"><div className="tray-copy"><Scale size={18} /><span><strong>{selected.length} {selected.length === 1 ? 'product' : 'products'}</strong> ready to compare</span></div><div className="tray-products">{selected.map((id) => { const product = products.find((item) => item.id === id); return product ? <span className="tray-pill" key={id}>{product.brand} {product.name}<button onClick={() => toggleCompare(id)} aria-label={`Remove ${product.name}`}><X size={13} /></button></span> : null })}</div><button className="compare-now" onClick={openComparison}>Compare now <ChevronRight size={16} /></button></div>}
    {showCalculator && <div className="modal-backdrop" onClick={() => setShowCalculator(false)}><aside className="calculator-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-header"><div><p className="section-kicker">LANDED COST ESTIMATE</p><h2>Would importing save you?</h2></div><button className="icon-button" onClick={() => setShowCalculator(false)} aria-label="Close calculator"><X size={20} /></button></div><div className="drawer-product"><img src={calculatorProduct.image} alt="" /><div><strong>{calculatorProduct.brand} {calculatorProduct.name}</strong><span>International offer from {calculatorProduct.importStore}</span></div></div><label className="drawer-field">Deliver to<input value={postalCode} onChange={(event) => setPostalCode(event.target.value)} /><span><MapPin size={14} /> Cape Town, South Africa</span></label><div className="cost-inputs"><label>Shipping<input type="number" value={shipping} onChange={(event) => setShipping(Number(event.target.value))} /></label><label>Estimated duty<input type="number" value={duty} onChange={(event) => setDuty(Number(event.target.value))} /></label><label>Import VAT<input type="number" value={vat} onChange={(event) => setVat(Number(event.target.value))} /></label><label>Courier fee<input type="number" value="180" readOnly /></label></div><div className="cost-breakdown"><div><span>Product price</span><strong>{formatZar(calculatorProduct.importPrice)}</strong></div><div><span>Shipping + fees</span><strong>{formatZar(shipping + duty + vat + 180)}</strong></div><div className="cost-total"><span>Estimated landed cost</span><strong>{formatZar(importedTotal)}</strong></div></div><div className={localSaving > 0 ? 'saving-callout positive' : 'saving-callout'}><Check size={17} /><div><strong>{localSaving > 0 ? `${formatZar(localSaving)} estimated saving` : 'Local option may be better value'}</strong><span>{localSaving > 0 ? 'before assigning a rand value to the local warranty' : 'The local price is competitive once import costs are included.'}</span></div></div><div className="estimate-note"><Info size={15} /> Estimate uses an exchange-rate snapshot and indicative import charges. Final fees are set by customs and the courier.</div><button className="full-button" onClick={() => setShowCalculator(false)}>Save this estimate <Heart size={17} /></button></aside></div>}
  </div>
}

function ComparisonSection({ products, onRemove }: { products: Product[]; onRemove: (id: number) => void }) {
  return <section id="compare-section" className="comparison-section"><div className="comparison-heading"><div><p className="section-kicker">YOUR SHORTLIST</p><h2>Side by side, clearly.</h2><p>Compare the signals that matter before you spend.</p></div><span className="comparison-count">{products.length} of 3 slots used</span></div><div className="comparison-table"><div className="comparison-labels"><span>Product</span><span>Quality score</span><span>Local price</span><span>Import estimate</span><span>Battery</span><span>Noise cancelling</span></div>{products.map((product) => { const landed = product.importPrice + product.importShipping + Math.round(product.importPrice * 0.1) + Math.round((product.importPrice + product.importShipping) * 0.15) + 180; return <div className="comparison-product" key={product.id}><div className="comparison-product-name"><img src={product.image} alt="" /><div><small>{product.brand}</small><strong>{product.name}</strong></div><button onClick={() => onRemove(product.id)} aria-label={`Remove ${product.name}`}><X size={15} /></button></div><strong className="comparison-value quality-value">{product.score}/100</strong><strong className="comparison-value">{formatZar(product.localPrice)}</strong><strong className="comparison-value import-value">{formatZar(landed)}</strong><strong className="comparison-value">{product.battery}</strong><strong className="comparison-value">{product.anc}</strong></div> })}</div></section>
}

function ProductCard({ product, selected, onCompare, onCalculate }: { product: Product; selected: boolean; onCompare: () => void; onCalculate: () => void }) {
  const landed = product.importPrice + product.importShipping + Math.round(product.importPrice * 0.1) + Math.round((product.importPrice + product.importShipping) * 0.15) + 180
  return <article className="product-card"><div className="product-image" style={{ background: product.accent }}><img src={product.image} alt={`${product.brand} ${product.name}`} /><span className="product-tag">{product.tag}</span><button className="heart-button" aria-label={`Save ${product.name}`}><Heart size={17} /></button></div><div className="product-body"><div className="product-brand">{product.brand}</div><h3>{product.name}</h3><div className="rating"><span className="stars"><Star size={13} fill="currentColor" /> {product.rating}</span><span>{product.reviews} reviews</span><span className="quality-score">{product.score} quality</span></div><div className="spec-row"><span><strong>{product.anc}</strong><small>Noise cancelling</small></span><span><strong>{product.battery}</strong><small>Battery</small></span><span><strong>{product.weight}</strong><small>Weight</small></span></div><div className="price-row"><div><small>From</small><strong>{formatZar(product.localPrice)}</strong><span>{product.localStore} · local</span><a className="buy-link" href={product.localUrl} target="_blank" rel="noreferrer">Buy local <ExternalLink size={11} /></a></div><div className="import-price"><small>Import estimate</small><strong>{formatZar(landed)}</strong><span>{product.importStore} · landed</span><a className="buy-link" href={product.importUrl} target="_blank" rel="noreferrer">Buy import <ExternalLink size={11} /></a></div></div><div className="card-actions"><button className={selected ? 'compare-button selected' : 'compare-button'} onClick={onCompare}>{selected ? <Check size={15} /> : <Plus size={15} />} {selected ? 'Comparing' : 'Compare'}</button><button className="calculate-button" onClick={onCalculate}><Calculator size={15} /> Import check</button></div></div></article>
}

export default App
